---
title: "Process hand2 bud stage scRNA-seq R Notebook"
output:
  github_document: default
  html_document:
    df_print: paged
---

```{r libraries, results='hide', message=FALSE, warning=FALSE, error=FALSE}
library(Seurat)
library(sctransform)
library(ggplot2)
library(dplyr)
library(ggsci)
library(cowplot)
library(patchwork)
options(future.globals.maxSize = 4000 * 1024^2)
```

```{r mypal}
mypal <- pal_ucscgb(palette = "default",alpha = 1)(25)
cbpal18 <- c("#68023F","#008169","#EF0096","#00DCB5","#FFCFE2",
           "#003C86","#9400E6","#009FFA","#FF71FD","#7CFFFA",
           "#6A0213","#008607","#F60239","#00E307","#FFDC3D","#ffea8a","#001310","#ffe9f1")
```

```{r}
seurat <- readRDS(file = "RDSfiles/hand2.bud.clustered.RDS")
```

```{r}
Idents(seurat) <- "sub.cluster"
DimPlot(seurat, cols = cbpal18)
```
```{r}
Idents(seurat) <- "sub.cluster"
seurat <- RenameIdents(seurat,
                       "cardiomyocytes" = "myocardium",
                       "paraxial mesoderm 1" = "uncommitted PLPM",
                       "paraxial mesoderm 2" = "paraxial mesoderm",
                       "endothalial and hematopoietic precursors" = "endothelial and hematopoietic precursors",
                       "posterior lateral plate mesoderm" = "PLPM")
levels(seurat) <- c("endothelial and hematopoietic precursors","cranial mesoderm",
                    "ribosomal","myocardium","pericardium","mesothelium","PLPM",
                    "posterior hemangioblasts & kidney","paraxial mesoderm","uncommitted PLPM",
                    "pan-neuronal","neural plate","epidermal","endoderm 1","endoderm 2",
                    "notochord","prechordal plate & hatching gland 1","prechordal plate & hatching gland 2")
```


```{r, fig.width=7, fig.height=5}
p <- DimPlot(seurat, cols = cbpal18)
p
ggsave(filename = "results/hand2_bud_umap_vs2.png", plot = p, width = 7, height = 5, units = "in")
```

```{r}
Idents(seurat) <- "sub.cluster"
DimPlot(seurat, cols = cbpal18)
```

```{r}
genelist <- c("tcf21", "sema3aa", "wt1a", "meis3", "adra1d", "kank1a",
              "jam2b", "sfrp5", "tmem88b", "nr2f1a", "meis2b", "twist1a",
              "tbx20", "mef2ca", "hey2", "actn2b","ttn.2", "nkx2.5")
```

```{r, fig.width=7, fig.height=3}
p <- DotPlot(seurat, features = genelist, idents = c("pericardium","myocardium","mesothelium")) + RotatedAxis()
p
ggsave(filename = "results/dotplot.png", plot = p, width = 7, height = 3, units = "in")
```


```{r, fig.width=15, fig.height=10}
p <- FeaturePlot(seurat, features = genelist, keep.scale = "all", max.cutoff = 1.7, combine = F)
p <- wrap_plots(p, guides = "collect", ncol = 6) & theme(axis.title = element_text(size = 8), 
                                               axis.text = element_blank(),
                                               axis.ticks = element_blank())
p
ggsave(filename = "results/featurePlot_list1.png", plot = p, width = 15, height = 10, units = "in")
```

```{r}
genelist2 <- c("tmem88b", "sfrp5", "dhrs3a", "fzd7a", "tcf21", "fzd4", "fzd9b", "dact1", "dact3a", "tcf12")
```

```{r, fig.width=10, fig.height=5}
p <- FeaturePlot(seurat, features = genelist2, keep.scale = "all", max.cutoff = 1.7, combine = F)
p <- wrap_plots(p, guides = "collect", ncol = 5) & theme(axis.title = element_text(size = 8), 
                                               axis.text = element_blank(),
                                               axis.ticks = element_blank())
p
ggsave(filename = "results/featurePlot_list2.png", plot = p, width = 10, height = 5, units = "in")
```

saving cluster name changes -- this means notebook can't be run again without first rerunning Process_hand2.bud.Rmd
```{r}
seurat$sub.cluster <- Idents(seurat)
Idents(seurat) <- "sub.cluster"
levels(seurat)
```
```{r}
saveRDS(seurat, file = "RDSfiles/hand2.bud.clustered.RDS")
```


```{r}
sessionInfo()
```

