---
title: "Process hand2 bud stage scRNA-seq R Notebook"
output:
  html_document:
    df_print: paged
  github_document: default
---

```{r libraries, results='hide', message=FALSE, warning=FALSE, error=FALSE}
library(Seurat)
library(sctransform)
library(ggplot2)
library(dplyr)
library(ggsci)
library(cowplot)
library(patchwork)
options(future.globals.maxSize = 4000 * 1024^2)
```

```{r mypal}
mypal <- pal_ucscgb(palette = "default",alpha = 1)(25)
cbpal18 <- c("#68023F","#008169","#EF0096","#00DCB5","#FFCFE2",
           "#003C86","#9400E6","#009FFA","#FF71FD","#7CFFFA",
           "#6A0213","#008607","#F60239","#00E307","#FFDC3D","#ffea8a","#001310","#ffe9f1")
```

```{r getqcplots, fig.height=5, fig.width=7  }
GetQCplots <- function(seurat, mitoPattern){
  seurat[["percent.mt"]] <- PercentageFeatureSet(seurat, pattern = mitoPattern)
  v <- VlnPlot(seurat, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
  f1 <- FeatureScatter(seurat, feature1 = "nCount_RNA", feature2 = "percent.mt")
  f2 <- FeatureScatter(seurat, feature1 = "nFeature_RNA", feature2 = "percent.mt")
  f3 <- FeatureScatter(seurat, feature1 = "nCount_RNA", feature2 = "nFeature_RNA")
  
  qc1 <- ggplot(seurat@meta.data, aes(x=nCount_RNA, y=nFeature_RNA, color=percent.mt)) + geom_point(size=0.1) +
    scale_color_gradient(low="blue",high="red") + theme_classic()

  qc2 <- ggplot(seurat@meta.data, aes(x=nCount_RNA, y=percent.mt)) + geom_point(size=0.1) + scale_x_log10() +
    geom_density2d()

  qc3 <- ggplot(seurat@meta.data, aes(x=nCount_RNA, y=nFeature_RNA ,color=percent.mt)) + geom_point(size=0.1) +
    scale_x_log10() + scale_y_log10() + geom_density2d() +
    scale_color_gradient(low="gray",high="darkblue") + theme_classic()

  print(v)
  print(f1)
  print(f2)
  print(f3)
  print(qc1)
  print(qc2)
  print(qc3)

  return(seurat)
}
```

# Load data
```{r loaddata, results='hide', message=FALSE, warning=FALSE, error=FALSE}
seurat_data <- Read10X(data.dir = "~/Documents/Projects/Mosimann/Mosimann_scRNAseq/data/budstage_drlmCherry_hand2GFP/")
seurat <- CreateSeuratObject(seurat_data, project = "hand2_bud")
```

# QC data
```{r runqc, fig.height=5, fig.width=7  }
seurat <- GetQCplots(seurat, "^mt-")
```

```{r subset, results='hide', message=FALSE, warning=FALSE, error=FALSE}
seurat <- subset(seurat, 
               subset = nFeature_RNA > 1500
               & percent.mt < 5)
seurat
```

# Normalization
```{r normalize}
seurat <- NormalizeData(seurat, verbose = F)
seurat <- FindVariableFeatures(seurat, nfeatures = 2000, selection.method = "vst", verbose = F)
all.genes <- rownames(seurat)
seurat <- ScaleData(seurat, features = all.genes, verbose = F)
```

# Perform Dimensionality
```{r dimred, results='hide', message=FALSE, warning=FALSE, error=FALSE, fig.height=7, fig.width=7  }
DefaultAssay(seurat) <- "RNA"
seurat <- RunPCA(seurat, verbose = F, npcs = 50)
ElbowPlot(seurat, ndims = 50)
```

```{r umap, results='hide', message=FALSE, warning=FALSE, error=FALSE}
seurat <- RunUMAP(seurat, dims = 1:20, verbose = F)
seurat <- FindNeighbors(seurat, verbose = F, dims = 1:20)
```

```{r clusters, results='hide', message=FALSE, warning=FALSE, error=FALSE}
seurat <- FindClusters(seurat, resolution = 0.8, verbose = F)
```

```{r plot1}
DimPlot(seurat, label = T, repel = T) + scale_color_igv() + ggtitle("res 0.8")
```

```{r rename}
Idents(seurat) <- "RNA_snn_res.0.8"
seurat <- RenameIdents(seurat,
                       "0" = "posterior hemangioblasts & kidney",
                       "1" = "endothalial and hematopoietic precursors",
                       "2" = "cardiomyocytes",
                       "3" = "posterior lateral plate mesoderm",
                       "4" = "mesothelium",
                       "5" = "pan-neuronal",
                       "6" = "ribosomal",
                       "7" = "endoderm 1",
                       "8" = "endoderm 2",
                       "9" = "prechordal plate & hatching gland 1",
                       "10" = "epidermal",
                       "11" = "tailbud",
                       "12" = "cranial mesoderm",
                       "13" = "neural plate",
                       "14" = "prechordal plate & hatching gland 2",
                       "15" = "paraxial mesoderm",
                       "16" = "notochord")
seurat$Clusters <- Idents(seurat)
DimPlot(seurat, label = T, label.size = 3) + NoLegend() + scale_color_igv()
```

```{r subcluster}
seurat <- FindSubCluster(seurat, cluster = "mesothelium", graph.name = "RNA_snn", resolution = 0.2)
DimPlot(seurat, group.by = "sub.cluster", label = T, label.size = 2) + NoLegend() + scale_color_igv()
```

```{r rename2}
Idents(seurat) <- "sub.cluster"
seurat <- RenameIdents(seurat,
                       "mesothelium_0" = "pericardium",
                       "mesothelium_1" = "mesothelium")
seurat$sub.cluster <- Idents(seurat)
DimPlot(seurat, label = T, label.size = 2) + NoLegend() + scale_color_igv()
```

```{r save}
if (!dir.exists("RDSfiles")){
  dir.create("RDSfiles")
}
saveRDS(seurat, file = "RDSfiles/hand2.bud.clustered.RDS")
```

```{r sessioninfo}
sessionInfo()
```



